### ISSUE TITLE
TypeError: boolean false is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by jacargentina** [strapi/migration-scripts#7]
### Required System information

- Node.js version:  18
- NPM version: 8.6.0
- Source Strapi version: 3.6.8
- Target Strapi version: 4.1.5
- Source Database: strapi-production
- Target Database: strapi-production-v4
- Operating system: macos
- Which script are you running: v3-sql-v4-sql 

### Describe the bug

This output I got when trying to migrate

```
Migrating Core Store TBA
Migrating 59/79 items from core_store to strapi_core_store_settings
core_store batch #1
core_store batch #2
Migrating Admin
Migrating 3 items from strapi_role to admin_roles
strapi_role batch #1
Migrating 1 items from strapi_administrator to admin_users
strapi_administrator batch #1
Migrating 1 items from strapi_users_roles to admin_users_roles_links
strapi_users_roles batch #1
Migrating 135 items from strapi_permission to admin_permissions
strapi_permission batch #1
strapi_permission batch #2
strapi_permission batch #3
Migrating Users
Migrating 3 items from users-permissions_role to up_roles
users-permissions_role batch #1
Migrating 198/486 items from users-permissions_permission to up_permissions
users-permissions_permission batch #1
users-permissions_permission batch #2
users-permissions_permission batch #3
users-permissions_permission batch #4
Migrating 416 items from users-permissions_user to up_users
users-permissions_user batch #1
users-permissions_user batch #2
users-permissions_user batch #3
users-permissions_user batch #4
users-permissions_user batch #5
users-permissions_user batch #6
users-permissions_user batch #7
users-permissions_user batch #8
users-permissions_user batch #9
Migration custom  01_my-custom-migration.js
Migrate webhooks
Migrating 0 items from strapi_webhooks to strapi_webhooks
Migrate locales (i18n)
SOURCE TABLE i18n_locales DOES NOT EXISTS
Migrating components
Migrating files
Migrating 1881 items from upload_file to files
upload_file batch #1
upload_file batch #2
upload_file batch #3
upload_file batch #4
upload_file batch #5
upload_file batch #6
upload_file batch #7
upload_file batch #8
upload_file batch #9
upload_file batch #10
upload_file batch #11
upload_file batch #12
upload_file batch #13
upload_file batch #14
upload_file batch #15
upload_file batch #16
upload_file batch #17
upload_file batch #18
upload_file batch #19
upload_file batch #20
upload_file batch #21
upload_file batch #22
upload_file batch #23
upload_file batch #24
upload_file batch #25
upload_file batch #26
upload_file batch #27
upload_file batch #28
upload_file batch #29
upload_file batch #30
upload_file batch #31
upload_file batch #32
upload_file batch #33
upload_file batch #34
upload_file batch #35
upload_file batch #36
upload_file batch #37
upload_file batch #38
Migrating 1751 items from upload_file_morph to files_related_morphs
upload_file_morph batch #1
upload_file_morph batch #2
upload_file_morph batch #3
upload_file_morph batch #4
upload_file_morph batch #5
upload_file_morph batch #6
upload_file_morph batch #7
upload_file_morph batch #8
upload_file_morph batch #9
upload_file_morph batch #10
upload_file_morph batch #11
upload_file_morph batch #12
upload_file_morph batch #13
upload_file_morph batch #14
upload_file_morph batch #15
upload_file_morph batch #16
upload_file_morph batch #17
upload_file_morph batch #18
upload_file_morph batch #19
upload_file_morph batch #20
upload_file_morph batch #21
upload_file_morph batch #22
upload_file_morph batch #23
upload_file_morph batch #24
upload_file_morph batch #25
upload_file_morph batch #26
upload_file_morph batch #27
upload_file_morph batch #28
upload_file_morph batch #29
upload_file_morph batch #30
upload_file_morph batch #31
upload_file_morph batch #32
upload_file_morph batch #33
upload_file_morph batch #34
upload_file_morph batch #35
upload_file_morph batch #36
Migrating Models
Migrating 90 items from customer to customer
customer batch #1
/Users/javiercastro/git/migration-scripts/v3-sql-v4-sql/migrate/migrateModels.js:182
      const [createdAt, updatedAt] = modelDef.options.timestamps;
                                     ^

TypeError: boolean false is not iterable (cannot read property Symbol(Symbol.iterator))
    at /Users/javiercastro/git/migration-scripts/v3-sql-v4-sql/migrate/migrateModels.js:182:38
    at Array.map (<anonymous>)
    at migrateItems (/Users/javiercastro/git/migration-scripts/v3-sql-v4-sql/migrate/helpers/migrateFields.js:25:6)
    at migrate (/Users/javiercastro/git/migration-scripts/v3-sql-v4-sql/migrate/helpers/migrate.js:122:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async migrateModels (/Users/javiercastro/git/migration-scripts/v3-sql-v4-sql/migrate/migrateModels.js:181:5)
    at async migrate (/Users/javiercastro/git/migration-scripts/v3-sql-v4-sql/migrate/index.js:70:3)
    at async f (/Users/javiercastro/git/migration-scripts/v3-sql-v4-sql/index.js:6:3)

Node.js v18.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce the behavior

Configure .env and do yarn start

### Expected behavior

Just work.

**Comment by LucaNerlich** [comment]
without further info / schema examples / model examples this is not reproducible

**Comment by jacargentina** [comment]
By looking at the code, the table `core_store` has the data.

[test.csv](https://github.com/strapi/migration-scripts/files/8632101/test.csv)

Is any other thing I can send?

**Comment by LucaNerlich** [comment]
Quite possible, that they forgot that it is/was possible to disable the timestamps alltogether. Could you post example data / schemas from your v3 and v4 database and json models / content-types?

That would help to understand what the script is trying to do and why it fails.
